feat: lexpol integration
govpf/mes-demarches pull request #47
Opened 2024-12-12 13:15 UTC by yhru

2025-01-07 01:04 UTC, maatinito requested changes

2025-01-07 01:04 UTC, maatinito commented on app/components/types_de_champ_editor/champ_component/champ_component.html.haml
> +                    %p Aucune modèle disponible ou erreur lors de la récupération des modèles.
Aucune modèle ?

2025-01-07 01:04 UTC, maatinito commented on app/components/types_de_champ_editor/champ_component/champ_component.html.haml
> +                - if lexpol_models.any?
Les modèles devraient être triée ET tronqués à 40 caractères

2025-01-07 01:04 UTC, maatinito commented on app/controllers/instructeurs/dossiers_controller.rb
> +      mapping = (champ.type_de_champ.lexpol_mapping || "")
je pensais que l'on mettait un mapping par ligne (\n) et non des virgules

2025-01-07 01:04 UTC, maatinito commented on app/controllers/instructeurs/dossiers_controller.rb
> +      variables = dossier.champs.each_with_object({}) do |champ, hash|
je comprends l'interet d'envoyer toutes les variables (par défaut pas de configuration)
En meme temps: 
* il faut aussi envoyer les annotations 
* il faut pouvoir indiquer que la variable lexpol toto.tutu est égal au champ Numéro_DN.date_de_naissance ou que la variable lexpol demande.date est égal à la date de dépot du dossier (ce n'est pas un champ)
* le code devrait etre factorisé dans lexpol api

2025-01-07 01:04 UTC, maatinito commented on app/controllers/instructeurs/dossiers_controller.rb
> +    def create_lexpol_dossier
pourquoi cela semble faire doublon avec le lexpol controller ?

2025-01-07 01:04 UTC, maatinito commented on app/models/concerns/lexpol_concern.rb
> +    lexpol_service = APILexpol.new
un peu dommage de réinitialiser un lexpol api alors qu'il est créé juste au dessus ? 
est-ce que cela va demander un nouveau token ?

2025-01-07 01:04 UTC, maatinito commented on app/views/shared/dossiers/_edit_annotations.html.haml
> +          - if champ_lexpol.data&.[]('lexpol_dossier_url').present?
je pense que ca devrait etre un lien sur le numéro NOR plutot qu'un bouton : ce n'est pas une action mais bien un lien vers une autre page

2025-01-07 01:04 UTC, maatinito commented on app/services/api_lexpol.rb
> +      email_agent: ENV.fetch('API_LEXPOL_AGENT_EMAIL')
Le mail de l'agent : c'est le mail sous lequel tu es connecté en ce moment... 
Chaque fois qu'un agent va travailler dans mes-demarches, il faut qu'il le fasse en son nom. 
Donc, le initialize devrait prendre à chaque fois le user courant. 
Pb : notre mail n'est pas enregistré sur lexpol pour l'instant. Faut que je vois comment faire mais à priori je dirais que tu peux patcher en disant si le mail du user courant finit en .gov.pf alors c'est ce mail qu'il faut utiliser sinon prendre API_LEXPOL_AGENT_EMAIL.
Et du coup, ca me fait penser qu'un user peut ne pas avoir le droit de manipuler la partie lexpol et il faudra que Mes-Démarches grise les actions sur le dossier...

2025-01-07 11:04 UTC, yhru commented on app/components/types_de_champ_editor/champ_component/champ_component.html.haml
> +                - if lexpol_models.any?
Pour le tri, on le fait par ordre alphabétique ?

2025-01-14 19:55 UTC, maatinito commented on app/components/types_de_champ_editor/champ_component/champ_component.html.haml
> +                - if lexpol_models.any?
est-ce que tu verrais un ordre différent ?

2025-01-14 21:11 UTC, yhru commented on app/components/types_de_champ_editor/champ_component/champ_component.html.haml
> +                - if lexpol_models.any?
Actuellement il me semble que c'est dans l'ordre antéchronologique

Je ne sais pas comment les utilisateurs finaux vont se servir de cette liste si tu en préfère un à un autre je peux changer

2025-02-11 23:33 UTC, merged